### ISSUE TITLE
markCurrentLine

### ISSUE THREAD

**Issue by sensornew** [ccalfje/YiYiMark#1]
hi,  茫茫人海中遇到你，非常喜欢你的这个作品

有几点建议
1. 在打标签的时候，是否可以直接使用当前行的内容作为名字，不需要再手动输入内容，这样效率就高多了
2. 看你这边的开源代码还没有更新到0.1.2， 后续是不打算开源了吗？

**Comment by ccalfje** [comment]
> hi, 茫茫人海中遇到你，非常喜欢你的这个作品
> 
> 有几点建议
> 
> 1. 在打标签的时候，是否可以直接使用当前行的内容作为名字，不需要再手动输入内容，这样效率就高多了
> 2. 看你这边的开源代码还没有更新到0.1.2， 后续是不打算开源了吗？

1.很好的建议，近期我修改一下。
2.^_^，忘记push了，并没有不开源的打算。

**Comment by sensornew** [comment]
Great,  thanks very much
另外有计划支持 multi root 吗?

**Comment by ccalfje** [comment]
> Great, thanks very much 另外有计划支持 multi root 吗?

这个可能不太好搞，改天我再想想

**Comment by ccalfje** [comment]
已支持直接使用当前行的内容作为名字。同时添加了一个配置选项，可以关闭该行为。
issue关闭
